pipeline {
    agent any

    tools {
        maven 'M3'
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Docker Build') {
            steps {
                echo 'Building Docker Image...'
                // This command creates a Docker Image named "my-simple-app"
                // The "." at the end tells it to look for the Dockerfile in the current folder
                sh 'docker build -t my-simple-app .'
            }
        }

        stage('Deploy Local') {
            steps {
                echo 'Deploying App Locally...'
                // This stops any old version of the app and starts the new one
                sh 'docker rm -f my-app-container || true'
                sh 'docker run -d --name my-app-container my-simple-app'
                echo 'App is now running as a container!'
            }
        }
    }
}
